version: "3.8"

services:
  fridge:
    image: antechrestos/observability-tutorial-fridge:latest
    environment:
      SPRING_ACTIVE_PROFILE: docker,log_file,requests-attributes-in-mdc,sleuth
      SPRING_MAIN_BANNER_MODE: off
      LOG_DIRECTORY: /log
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    networks:
      - observability_tutorial
    volumes:
      - observability_tutorial:/log

  burger-maker:
    image: antechrestos/observability-tutorial-burger-maker:latest
    environment:
      FRIDGE_HOST: fridge
      SPRING_ACTIVE_PROFILE: docker,log_file,requests-attributes-in-mdc,sleuth
      SPRING_MAIN_BANNER_MODE: off
      LOG_DIRECTORY: /log
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    depends_on:
      - fridge
    ports:
      - "8080:8080"
    networks:
      - observability_tutorial
    volumes:
      - observability_tutorial:/log

networks:
  observability_tutorial:
    external: true
    name: observability_tutorial

volumes:
  observability_tutorial:
    external: true
    name: observability_tutorial
