version: "3.8"

services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.69.0
    command: [ "--config=/etc/otel-collector/config.yml" ]
    ports:
      - "8889:8889"
    volumes:
      - ./otel-collector:/etc/otel-collector/
    networks:
      - observability_tutorial

  fridge:
    image: antechrestos/observability-tutorial-fridge:latest
    environment:
      JVM_OPTIONS: "-javaagent:/opt/opentelemetry-javaagent.jar"
      SPRING_ACTIVE_PROFILE: docker,log_file
      SPRING_MAIN_BANNER_MODE: off
      LOG_DIRECTORY: /log
      OTEL_TRACES_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_TIMEOUT: "2s"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=fridge,application.name=burger_maker"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    networks:
      - observability_tutorial
    volumes:
      - observability_tutorial:/log

  burger-maker:
    image: antechrestos/observability-tutorial-burger-maker:latest
    environment:
      JVM_OPTIONS: "-javaagent:/opt/opentelemetry-javaagent.jar"
      FRIDGE_HOST: fridge
      SPRING_ACTIVE_PROFILE: docker,log_file
      SPRING_MAIN_BANNER_MODE: off
      LOG_DIRECTORY: /log
      OTEL_TRACES_EXPORTER: "none"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
      OTEL_EXPORTER_OTLP_TIMEOUT: "2s"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=burger_maker,application.name=burger_maker"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 128M
    depends_on:
      - fridge
    ports:
      - "8080:8080"
    networks:
      - observability_tutorial
    volumes:
      - observability_tutorial:/log

networks:
  observability_tutorial:
    external: true
    name: observability_tutorial

volumes:
  observability_tutorial:
    external: true
    name: observability_tutorial
