receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 5
    send_batch_max_size: 10
    timeout: 2s

exporters:
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200



service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch ]
      exporters: [ prometheus ]
    traces:
      receivers: [otlp]
      processors: [batch ]
      exporters: [ otlp/tempo ]