server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: service_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: services
          __path__: /logs/*.log
    pipeline_stages:
      - multiline:
          firstline: "^{"
      - json:
          expressions:
            application: '"service.name"'
            service: '"service.node.name"'
            date: '"@timestamp"'
            httpMethod: '"request.method"'
            httpPath: '"request.uri"'
      - replace:
          expression: ".*([Z])$"
          source: "date"
          replace: "000000-00:00"
      - replace:
          expression: "(traceId)"
          replace: "traceID"
      - replace:
          expression: "(spanId)"
          replace: "spanID"
      - timestamp:
          source: 'date'
          format: RFC3339Nano
      - labels:
          application:
          service:
          httpMethod:
          httpPath:
