version: '3.9'

networks:
  observability_tutorial:
    external: true
    name: observability_tutorial

volumes:
  observability_tutorial:
    external: true
    name: observability_tutorial


services:
  grafana:
    image: grafana/grafana-oss:9.3.2
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
    networks:
      - observability_tutorial

  loki:
    image: grafana/loki:2.7.1
    command:
      - -config.file
      - /etc/loki/config.yml
    volumes:
      - ./loki:/etc/loki:ro
    networks:
      - observability_tutorial

  promtail:
    image: grafana/promtail:2.7.1
    command:
      - -config.file
      - /etc/promtail/config.yml
    volumes:
      - ./promtail:/etc/promtail:ro
      - observability_tutorial:/logs
    networks:
      - observability_tutorial

  tempo:
    image: grafana/tempo:1.5.0
    command: --config.file=/etc/tempo/config.yml
    volumes:
      - ./tempo:/etc/tempo:ro
    networks:
      - observability_tutorial

  prometheus:
    image: bitnami/prometheus:2.41.0
    volumes:
      - ./prometheus:/etc/prometheus:ro
    networks:
      - observability_tutorial

