version: '3.9'


services:
  grafana:
    image: grafana/grafana-oss:9.2.0

  loki:
    image: grafana/loki:2.6.1

  promtail:
    image: grafana/promtail:2.6.1

  prometheus:
    image: bitnami/prometheus:2.39.1