version: '3.9'


services:
  grafana:
    image: grafana/grafana-oss:9.3.2
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:2.7.1

  promtail:
    image: grafana/promtail:2.7.1

  prometheus:
    image: bitnami/prometheus:2.41.0