apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    version: 1
    uid: loki
    editable: true
    url: http://loki:3100
    isDefault: true
    basicAuth: false
    jsonData: {}
