global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
          - "otel-collector:8889"